version: '3'

services:
  yggdrasil:
    container_name: yggdrasil
    env_file: .env
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '3333:3333'
    volumes:
      - ./:/usr/src/app/
    networks:
      - bifrost

# docker network create --driver bridge bifrost
networks:
  bifrost:
    external: true
