services:
  yggdrasil:
    container_name: yggdrasil
    env_file: .env
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '3333:3333'
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - yggdrasil-db
    networks:
      - bifrost
      - main

  yggdrasil-db:
    container_name: yggdrasil-db
    env_file: .env
    image: mongo:latest
    build:
      context: ./
      dockerfile: ./database/Dockerfile
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - bifrost

networks:
  main:
  bifrost:
    external: false # externa true, docker d'nt create network

volumes:
  mongo_data:
